-- DROP DATABASE IF EXISTS IAF;

CREATE DATABASE IAF
  WITH OWNER = IAF
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'Portuguese, Brazil'
       LC_CTYPE = 'Portuguese, Brazil'
       CONNECTION LIMIT = -1;
---------------------------------------------------------------
CREATE SEQUENCE USU_SM_USUARIOS_ID_SEQ
      INCREMENT 1
       MINVALUE 1
       MAXVALUE 32767
          START 1
          CACHE 1;
          
CREATE TABLE USUARIOS (SM_USUARIOS_ID smallint    NOT NULL DEFAULT NEXTVAL('USU_SM_USUARIOS_ID_SEQ')
                      ,VA_NOME        varchar(64)
                      ,VA_LOGIN       varchar(16) NOT NULL
                      ,CH_SENHA       char(128)   NOT NULL
                      ,VA_EMAIL       varchar(64) NULL
                      ,CONSTRAINT PK_USU PRIMARY KEY (SM_USUARIOS_ID)
                      ,CONSTRAINT UC_USU_VA_LOGIN UNIQUE (VA_LOGIN )
                      ,CONSTRAINT UC_USU_VA_EMAIL UNIQUE (VA_EMAIL)
);

ALTER SEQUENCE USU_SM_USUARIOS_ID_SEQ 
      OWNED BY USUARIOS.SM_USUARIOS_ID;
---------------------------------------------------------------
CREATE SEQUENCE GRU_SM_GRUPOS_ID_SEQ
      INCREMENT 1
       MINVALUE 1
       MAXVALUE 32767
          START 1
          CACHE 1;

CREATE TABLE GRUPOS (SM_GRUPOS_ID smallint     NOT NULL DEFAULT NEXTVAL('GRU_SM_GRUPOS_ID_SEQ')
                    ,VA_NOME      varchar(64)  NOT NULL
                    ,VA_DESCRICAO varchar(128) NOT NULL
                    ,CONSTRAINT PK_GRU PRIMARY KEY (SM_GRUPOS_ID)
                    ,CONSTRAINT UC_GRU_VA_NOME UNIQUE (VA_NOME)
);
ALTER SEQUENCE GRU_SM_GRUPOS_ID_SEQ 
      OWNED BY GRUPOS.SM_GRUPOS_ID;
---------------------------------------------------------------
/*





CREATE TABLE GRUPOSDOSUSUARIOS (
  `MI_GRUPOSDOSUSUARIOS_ID` mediumint(8) NOT NULL AUTO_INCREMENT,
  `TI_GRUPOS_ID` tinyint(3) NOT NULL,
  `SM_USUARIOS_ID` smallint(5) NOT NULL,
  `SM_USUARIOCRIADOR_ID` smallint(5) unsigned DEFAULT NULL,
  `DT_DATAEHORADACRIACAO` datetime DEFAULT NULL,
  `SM_USUARIOMODIFICADOR_ID` smallint(5) unsigned DEFAULT NULL,
  `DT_DATAEHORADAMODIFICACAO` datetime DEFAULT NULL,
  `EN_SITUACAO` enum('INSERIDO','MODIFICADO','SINCRONIZADO') COLLATE latin1_bin DEFAULT NULL,
  PRIMARY KEY (`MI_GRUPOSDOSUSUARIOS_ID`),
  UNIQUE KEY `GDU_TI_GRUPOS_ID_SM_USUARIOS_ID_UI` (`TI_GRUPOS_ID`,`SM_USUARIOS_ID`),
  KEY `USU_GDU_IX` (`SM_USUARIOS_ID`),
  KEY `GRU_GDU_IX` (`TI_GRUPOS_ID`),
  CONSTRAINT `GRU_GDU_FK` FOREIGN KEY (`TI_GRUPOS_ID`) REFERENCES `grupos` (`TI_GRUPOS_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `USU_GDU_FK` FOREIGN KEY (`SM_USUARIOS_ID`) REFERENCES `usuarios` (`SM_USUARIOS_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=177 DEFAULT CHARSET=latin1 COLLATE=latin1_bin;

CREATE TABLE `permissoesdosusuarios` (
  `IN_PERMISSOESDOSUSUARIOS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `IN_ENTIDADESDOSISTEMA_ID` int(11) NOT NULL,
  `SM_USUARIOS_ID` smallint(5) NOT NULL,
  `TI_LER` tinyint(1) NOT NULL DEFAULT '0',
  `TI_INSERIR` tinyint(1) NOT NULL DEFAULT '0',
  `TI_ALTERAR` tinyint(1) NOT NULL DEFAULT '0',
  `TI_EXCLUIR` tinyint(1) NOT NULL DEFAULT '0',
  `SM_USUARIOCRIADOR_ID` smallint(5) unsigned DEFAULT NULL,
  `DT_DATAEHORADACRIACAO` datetime DEFAULT NULL,
  `SM_USUARIOMODIFICADOR_ID` smallint(5) unsigned DEFAULT NULL,
  `DT_DATAEHORADAMODIFICACAO` datetime DEFAULT NULL,
  `EN_SITUACAO` enum('INSERIDO','MODIFICADO','SINCRONIZADO') COLLATE latin1_bin DEFAULT NULL,
  PRIMARY KEY (`IN_PERMISSOESDOSUSUARIOS_ID`),
  UNIQUE KEY `PDU_IN_ENTIDADESDOSISTEMA_ID_SM_USUARIOS_ID_UI` (`IN_ENTIDADESDOSISTEMA_ID`,`SM_USUARIOS_ID`),
  KEY `USU_PDU_IX` (`SM_USUARIOS_ID`),
  KEY `EDS_PDU_IX` (`IN_ENTIDADESDOSISTEMA_ID`),
  CONSTRAINT `EDS_PDU_FK` FOREIGN KEY (`IN_ENTIDADESDOSISTEMA_ID`) REFERENCES `entidadesdosistema` (`IN_ENTIDADESDOSISTEMA_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `USU_PDU_FK` FOREIGN KEY (`SM_USUARIOS_ID`) REFERENCES `usuarios` (`SM_USUARIOS_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;

CREATE TABLE `permissoesdosgrupos` (
  `IN_PERMISSOESDOSGRUPOS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `IN_ENTIDADESDOSISTEMA_ID` int(11) NOT NULL,
  `TI_GRUPOS_ID` tinyint(3) NOT NULL,
  `TI_LER` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `TI_INSERIR` tinyint(1) NOT NULL DEFAULT '0',
  `TI_ALTERAR` tinyint(1) NOT NULL DEFAULT '0',
  `TI_EXCLUIR` tinyint(1) NOT NULL DEFAULT '0',
  `SM_USUARIOCRIADOR_ID` smallint(5) unsigned DEFAULT NULL,
  `DT_DATAEHORADACRIACAO` datetime DEFAULT NULL,
  `SM_USUARIOMODIFICADOR_ID` smallint(5) unsigned DEFAULT NULL,
  `DT_DATAEHORADAMODIFICACAO` datetime DEFAULT NULL,
  `EN_SITUACAO` enum('INSERIDO','MODIFICADO','SINCRONIZADO') COLLATE latin1_bin DEFAULT NULL,
  PRIMARY KEY (`IN_PERMISSOESDOSGRUPOS_ID`),
  UNIQUE KEY `PDG_IN_ENTIDADESDOSISTEMA_ID_TI_GRUPOS_UI` (`IN_ENTIDADESDOSISTEMA_ID`,`TI_GRUPOS_ID`),
  KEY `GRU_PDG_IX` (`TI_GRUPOS_ID`),
  KEY `EDS_PDG_IX` (`IN_ENTIDADESDOSISTEMA_ID`),
  CONSTRAINT `EDS_PDG_FK` FOREIGN KEY (`IN_ENTIDADESDOSISTEMA_ID`) REFERENCES `entidadesdosistema` (`IN_ENTIDADESDOSISTEMA_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `GRU_PDG_FK` FOREIGN KEY (`TI_GRUPOS_ID`) REFERENCES `grupos` (`TI_GRUPOS_ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=345 DEFAULT CHARSET=latin1 COLLATE=latin1_bin;


*/

CREATE TABLE USUARIOS
(
  BS_USUARIOS_ID bigserial NOT NULL,
  VA_NOME varchar(64) NOT NULL,
  VA_EMAIL varchar(40) NOT NULL,
  VA_LOGIN varchar(20) NOT NULL,
  CH_PASSWORD char(32) NOT NULL,
  PRIMARY KEY (BS_USUARIOS_ID)
);